Repository URECA-Cookie/Cookie-FE, pull requests merged in 2024-12, with the labels that each got.

#92 Fix/#90 axios mypage
  cookie/src/App.jsx
  cookie/src/components/matchup/Modal.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/styles/global.js
Labels: 🍿 Feat

#93 Feat 관리자페이지 등록된 영화리스트 화면 구현
  cookie/src/assets/images/admin/Edit.svg
  cookie/src/assets/images/admin/like.svg
  cookie/src/assets/images/admin/more.svg
  cookie/src/components/LoginModal.jsx
  cookie/src/components/admin/AddLinkStillCut.jsx
  cookie/src/components/admin/Addmovie.jsx
  cookie/src/components/admin/CookieMovieList.jsx
  cookie/src/components/admin/EditCategory.jsx
  cookie/src/components/admin/MovieInfoModal.jsx
  cookie/src/components/admin/MovieList.jsx
  cookie/src/components/admin/Pagination.jsx
  cookie/src/components/admin/SearchMovieDetail.jsx
  cookie/src/components/admin/SearchMovieList.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUp.jsx
  cookie/src/components/main/RankMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/config/OAuthConfig.js
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/admin/AdminLogin.jsx
  cookie/src/pages/admin/AdminMovie.jsx
  cookie/src/pages/main.jsx
  cookie/src/stores/useAdminMovieStore.js
  cookie/src/stores/useMovieGategoryStore.js
Labels: 🍿 Feat, 🚀 Refactor

#101 fix: axiosInstance 오류 수정
  cookie/src/api/auth/axiosInstance.js
Labels: 👿Bug

#94 Feat: 영화 리뷰 토큰으로 인증 처리
  cookie/src/pages/MovieReviewFeed.jsx
  cookie/src/pages/MovieReviewForm.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/ReviewFeed.jsx
  cookie/src/pages/ReviewForm.jsx
Labels: 🍿 Feat

#103 Feat 로그인 인증 상태관리 추가
  cookie/src/App.jsx
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/components/LoginModal.jsx
  cookie/src/pages/Login.jsx
  cookie/src/pages/admin/AdminLogin.jsx
  cookie/src/pages/main.jsx
  cookie/src/stores/useAuthStore.js
Labels: 🍿 Feat

#107 Design/#105 modify color
  cookie/public/firebase-messaging-sw.js
  cookie/src/firebase.js
  cookie/src/pages/MatchupPage.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/styles/global.js
Labels: 🚀 Refactor

#109 Refactor/#108 like movie review
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
Labels: 🚀 Refactor

#106 update: 회원가입 및 로그인 유저 상태관리 추가
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/components/signUp/Modal.jsx
  cookie/src/pages/Login.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/main.jsx
  cookie/src/stores/useUserStore.js
Labels: 🍿 Feat, 🚀 Refactor

#114 Feat:#113 회원탈퇴기능 추가
  cookie/src/pages/mypage.jsx
Labels: 🍿 Feat

#116 Feat 메인페이지 영화 데이터 api 연동
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUp.jsx
  cookie/src/components/main/RankMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/pages/main.jsx
  cookie/src/stores/useUserStore.js
  cookie/src/styles/global.js
Labels: 🍿 Feat

#112 Feature/#110 set pwafcm
  cookie/package-lock.json
  cookie/package.json
  cookie/public/192.png
  cookie/public/512.png
  cookie/public/firebase-messaging-sw.js
  cookie/public/romancebadge.svg
  cookie/src/App.jsx
  cookie/src/components/common/LoginModal.jsx
  cookie/src/components/common/Notification.jsx
  cookie/src/components/common/ScrollToTop.jsx
  cookie/src/components/common/ToggleSwitch.jsx
  cookie/src/config/OAuthConfig.js
  cookie/src/firebase.js
  cookie/src/firebase/firebase.js
  cookie/src/firebase/firebaseMessaging.js
  cookie/src/main.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/main.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/stores/notificationStore.js
  cookie/vite.config.js
  cookie/yarn.lock
Labels: 🍿 Feat

#118 Feat 배우 및 감독 상세페이지 구현
  cookie/src/assets/images/admin/goBack_br.svg
  cookie/src/components/common/LoginModal.jsx
  cookie/src/components/movieDetailPage/CastDetail.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#121 Feat/#120 mypage review detail
  cookie/src/assets/images/Notification.svg
  cookie/src/components/common/Notification.jsx
  cookie/src/components/common/ToggleSwitch.jsx
  cookie/src/components/mypage/LogoutAndWithdraw.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/config/OAuthConfig.js
  cookie/src/firebase/firebaseMessaging.js
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat

#126 Feature/#124 restrict guest access in my page
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/components/common/LoginModal.jsx
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/pages/ErrorPage.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/stores/useAuthStore.js
Labels: 🍿 Feat

#123 Feat: #77 영화 상세 페이지 API 연동 기본 작업
  cookie/src/components/movieDetailPage/CastSection.jsx
  cookie/src/components/movieDetailPage/DetailsSection.jsx
  cookie/src/components/movieDetailPage/GallerySection.jsx
  cookie/src/components/movieDetailPage/HeaderSection.jsx
  cookie/src/components/movieDetailPage/ReviewSection.jsx
  cookie/src/components/movieDetailPage/VideoSection.jsx
  cookie/src/components/searchpage/SearchResults.jsx
  cookie/src/pages/MovieDetail.jsx
  cookie/src/pages/search.jsx
Labels: 🍿 Feat, 🚀 Refactor

#129 Feat/#125 리뷰 좋아요 적용 & 특정 영화 리뷰 피드
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/pages/MovieReviewFeed.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🍿 Feat

#131 Feat/#130 review api 에러해결
  cookie/src/components/movieDetailPage/DetailsSection.jsx
  cookie/src/components/searchpage/SearchResultsForReview.jsx
  cookie/src/pages/MovieReviewFeed.jsx
  cookie/src/pages/MovieReviewForm.jsx
  cookie/src/pages/ReviewForm.jsx
  cookie/src/pages/SearchForReview.jsx
Labels: 🍿 Feat

#132 Feature/#128 cookie spinner
  cookie/index.html
  cookie/public/cookiespinner.svg
  cookie/src/assets/images/selected_home.svg
  cookie/src/assets/images/selected_matchup.svg
  cookie/src/assets/images/selected_profile.svg
  cookie/src/assets/images/selected_review.svg
  cookie/src/assets/images/selected_search.svg
  cookie/src/components/common/LoginModal.jsx
  cookie/src/components/common/Notification.jsx
  cookie/src/components/common/Spinner.jsx
  cookie/src/components/matchup/ChartSection.jsx
  cookie/src/components/matchup/Modal.jsx
  cookie/src/components/matchup/Poster.jsx
  cookie/src/components/matchup/PosterList.jsx
  cookie/src/components/matchup/ProgressBar.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/pages/Login.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat, 🚀 Refactor

#134 Update 메인페이지 반응형 적용
  cookie/src/components/admin/Addmovie.jsx
  cookie/src/components/admin/SideBar.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUp.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/components/movieDetailPage/CastDetail.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/admin/AdminLogin.jsx
  cookie/src/pages/admin/AdminMovie.jsx
  cookie/src/pages/main.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🚀 Refactor

#135 Feature/#133 mypage more review
  cookie/public/assets/images/cookiespinner.svg
  cookie/public/assets/images/mypage/ic_back.svg
  cookie/public/assets/images/mypage/manageprofile.svg
  cookie/public/assets/images/mypage/red-heart.svg
  cookie/public/assets/images/mypage/setdefaultImage.svg
  cookie/src/components/common/Spinner.jsx
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/GenreChart.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/MyAllReviewList.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#143 feat: 리뷰 댓글 수정시 모달창 구현
  cookie/src/pages/ReviewDetail.jsx
Labels: 🍿 Feat

#144 hotfix: 댓글 두번 입력되는 버그 수정
  cookie/src/pages/ReviewDetail.jsx
Labels: 🚀 Refactor

#147 Refactor: #136 메인페이지 영화 상세보기 경로 수정
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/GenreMovie.jsx
Labels: 🚀 Refactor

#149 Feature/#148 reissueor delete fcm token
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/pages/mypage.jsx
Labels: 🍿 Feat

#155 Refactor/#151 refactor match up
  cookie/public/assets/images/matchup/christmasversus.png
  cookie/public/assets/images/matchup/christmasversus.svg
  cookie/public/assets/images/matchup/matchupleftwin.png
  cookie/public/assets/images/matchup/matchuprightwin.png
  cookie/public/assets/images/matchup/snowman.png
  cookie/public/assets/images/matchup/versus.png
  cookie/src/assets/images/matchup/testposter.png
  cookie/src/assets/images/matchup/testposter1.png
  cookie/src/assets/images/matchup/topic_image.svg
  cookie/src/components/common/SnowEffect.jsx
  cookie/src/components/matchup/ChartSection.jsx
  cookie/src/components/matchup/Modal.jsx
  cookie/src/components/matchup/Poster.jsx
  cookie/src/components/matchup/PosterList.jsx
  cookie/src/components/matchup/ProgressBar.jsx
  cookie/src/components/matchup/RadarChart.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/components/mypage/ReviewContentSection.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/components/signUp/Modal.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/MyAllReviewList.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/stores/useUserStore.js
Labels: 🚀 Refactor

#158 Feat/#157 피드백 사항 개선
  cookie/src/components/movieDetailPage/GallerySection.jsx
  cookie/src/components/movieDetailPage/VideoSection.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/pages/MovieDetail.jsx
  cookie/src/pages/MovieReviewFeed.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🍿 Feat

#160 fix: #150 브랜치 오류 수정 커밋
  cookie/src/components/admin/AddLinkStillCut.jsx
  cookie/src/components/admin/Addmovie.jsx
  cookie/src/components/admin/CookieMovieList.jsx
  cookie/src/components/admin/EditCategory.jsx
  cookie/src/components/admin/MovieInfoModal.jsx
  cookie/src/components/admin/Pagination.jsx
  cookie/src/components/admin/SearchMovieDetail.jsx
  cookie/src/components/admin/SearchMovieList.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUp.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/stores/useUserStore.js
Labels: 🚀 Refactor

#165 Feat feedback 개선
  cookie/public/images/default.png
  cookie/src/components/movieDetailPage/CastDetail.jsx
  cookie/src/components/movieDetailPage/DetailsSection.jsx
  cookie/src/components/searchpage/SearchResults.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/ReviewForm.jsx
  cookie/src/pages/SearchForReview.jsx
  cookie/src/pages/search.jsx
Labels: 🍿 Feat

#166 Refactor : #163 메인페이지 리펙토링
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUp.jsx
  cookie/src/stores/useUserStore.js
Labels: 🚀 Refactor

#154 Feat: #153 메인페이지 UI 리팩토링
  cookie/public/assets/images/main/christmas-vs.png
  cookie/public/assets/images/main/like.svg
  cookie/public/assets/images/main/review.svg
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUpSection.jsx
  cookie/src/components/main/Question.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/pages/CategoryMovieFeed.jsx
  cookie/src/pages/main.jsx
  cookie/src/pages/search.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/styles/global.js
Labels: 🚀 Refactor

#169 Fix: 3차 피드백
  cookie/src/components/movieDetailPage/CastDetail.jsx
  cookie/src/components/movieDetailPage/CastSection.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🚀 Refactor

#172 Fix/#168 3차 피드백
  cookie/src/components/movieDetailPage/ReviewSection.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🚀 Refactor

#173 Refactor #170 메인 스크롤버튼 추가 및 로그인 모달 연결
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/pages/CategoryMovieFeed.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🚀 Refactor

#174 Feat/#168 3차feedback
  cookie/src/components/movieDetailPage/DetailsSection.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🍿 Feat

#164 Fix: 마이페이지 리팩토링
  .DS_Store
  cookie/.gitignore
  cookie/public/assets/images/mypage/ic_camera.svg
  cookie/public/firebase-messaging-sw.js
  cookie/src/assets/images/mypage/ic_back.svg
  cookie/src/assets/images/mypage/manageprofile.svg
  cookie/src/components/matchup/PointSection.jsx
  cookie/src/components/matchup/Poster.jsx
  cookie/src/components/matchup/ProgressBar.jsx
  cookie/src/components/mypage/BadgeList.jsx
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/LogoutAndWithdraw.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/PushNotificationToggle.jsx
  cookie/src/components/mypage/ReviewContentSection.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/PointHistoryPage.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/PrivateRoute.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#185 Feat: #182 매치업 페이지 히스토리 바로가기 버튼 수정
  cookie/public/assets/images/matchup/history.png
  cookie/src/components/matchup/TitleSection.jsx
Labels: 🚀 Refactor

#183 Feat:#178 로그인상태 주스탠드 펄시스턴트 적용
  cookie/src/pages/mypage.jsx
  cookie/src/stores/useAuthStore.js
Labels: 🍿 Feat

#187 Refactor/#184 refactor search page
  cookie/package-lock.json
  cookie/package.json
  cookie/public/assets/images/review/cookieinactive.svg
  cookie/public/assets/images/review/cookiescore.svg
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/components/movieDetailPage/CastDetail.jsx
  cookie/src/components/movieDetailPage/HeaderSection.jsx
  cookie/src/components/movieDetailPage/ReviewSection.jsx
  cookie/src/components/searchpage/MovieReviewDetailHeader.jsx
  cookie/src/components/searchpage/ReviewHeader.jsx
  cookie/src/components/searchpage/SearchResults.jsx
  cookie/src/pages/MovieDetail.jsx
  cookie/src/pages/MovieReviewFeed.jsx
  cookie/src/pages/MovieReviewForm.jsx
  cookie/src/pages/ReviewForm.jsx
  cookie/src/pages/search.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🚀 Refactor

#190 Fix: 일부 작은 버그 수정
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/components/mypage/PushNotificationToggle.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/Login.jsx
  cookie/src/pages/PointHistoryPage.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/stores/useAuthStore.js
Labels: 🚀 Refactor

#195 Fix/#186 리뷰 상세 로그인 전역상태관리 적용
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/search.jsx
Labels: 🚀 Refactor

#192 Feat:#191 푸쉬알림 on/off 기능 완성
  cookie/src/components/mypage/PushNotificationToggle.jsx
  cookie/src/pages/mypage.jsx
Labels: 🍿 Feat

#193 Feat : #177 관리자페이지 페이지네이션 적용
  cookie/src/App.jsx
  cookie/src/assets/images/admin/comment.svg
  cookie/src/assets/images/admin/heart.svg
  cookie/src/assets/images/admin/like2.svg
  cookie/src/assets/images/admin/message.svg
  cookie/src/assets/images/admin/recookie.svg
  cookie/src/assets/images/admin/review.svg
  cookie/src/assets/images/admin/ticket.svg
  cookie/src/assets/images/main/goBack_wh.svg
  cookie/src/components/admin/AddLinkStillCut.jsx
  cookie/src/components/admin/Addmovie.jsx
  cookie/src/components/admin/CookieMovieList.jsx
  cookie/src/components/admin/EditCategory.jsx
  cookie/src/components/admin/MovieInfoModal.jsx
  cookie/src/components/admin/Pagination.jsx
  cookie/src/components/admin/Reviews.jsx
  cookie/src/components/admin/SearchMovieDetail.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/pages/CategoryMovieFeed.jsx
  cookie/src/pages/Login.jsx
  cookie/src/pages/admin/AdminMovie.jsx
  cookie/src/pages/admin/AdminReviewLike.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🚀 Refactor

#200 Feat/#199 구글 애널리틱스 설정
  cookie/index.html
Labels: 🍿 Feat

#203 Refactor/#202 entire refactor
  cookie/src/components/layout/Footer.jsx
  cookie/src/components/layout/Header.jsx
  cookie/src/components/layout/MainContent.jsx
  cookie/src/components/mypage/LogoutAndWithdraw.jsx
  cookie/src/components/mypage/LogoutModal.jsx
  cookie/src/components/mypage/WithdrawModal.jsx
  cookie/src/components/signUp/Modal.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🚀 Refactor

#205 Fix/#201 4차 feedback
  cookie/src/components/searchpage/SearchResultsForReview.jsx
  cookie/src/pages/MovieDetail.jsx
  cookie/src/pages/SearchForReview.jsx
Labels: 🚀 Refactor

#206 Refactor: #204 전체적으로 리팩토링
  cookie/src/assets/images/login/google_OAuth.svg
  cookie/src/components/matchup/PointSection.jsx
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/LogoutAndWithdraw.jsx
  cookie/src/components/mypage/LogoutModal.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/PushNotificationToggle.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/components/mypage/WithdrawModal.jsx
  cookie/src/components/signUp/Modal.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/Login.jsx
  cookie/src/pages/PointHistoryPage.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/main.jsx
  cookie/src/pages/mypage.jsx
Labels: 🚀 Refactor

#207 feat: 리뷰 작성시 중복 등록 방지
  cookie/src/pages/ReviewForm.jsx
Labels: 🍿 Feat, 🚀 Refactor

#197 Refactor: 영화 리뷰 관련 페이지 UI 리팩토링
  cookie/public/assets/images/more-view.svg
  cookie/public/assets/images/notification.svg
  cookie/public/assets/images/prev-button.svg
  cookie/public/assets/images/review/comment-review-feed.svg
  cookie/public/assets/images/review/heart-review-feed.svg
  cookie/public/assets/images/review/score-macarong.png
  cookie/public/assets/images/review/ticket-skyblue.svg
  cookie/public/images/ticket.svg
  cookie/src/components/common/ManageModal.jsx
  cookie/src/components/common/Notification.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUpSection.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/components/searchpage/ReviewDetailHeader.jsx
  cookie/src/components/searchpage/ReviewTextSection.jsx
  cookie/src/components/searchpage/SearchBar.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/ReviewFeed.jsx
  cookie/src/pages/search.jsx
  cookie/src/styles/global.js
Labels: 🚀 Refactor

#209 Fix: #208 채팅 버그 수정
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/stores/useUserStore.js
Labels: 👿Bug

#215 Refactor/#211 review detail
  cookie/public/assets/images/cookie-logo.png
  cookie/public/assets/images/login/google.svg
  cookie/public/assets/images/login/naver.png
  cookie/public/assets/images/review/full-heart-review-feed.svg
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/config/OAuthConfig.js
  cookie/src/pages/Login.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🚀 Refactor

#217 Fix/#208 chatting bug fix1
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/pages/MatchupPage.jsx
Labels: 🚀 Refactor

#219 Refactor/#218 refactor match up chatting
  cookie/src/assets/images/matchup/chatsendbutton.svg
  cookie/src/components/layout/Header.jsx
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/PointHistoryPage.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/mypage.jsx
Labels: 🚀 Refactor

#220 Refactor: #216 영화 상세보기 페이지 UI 리팩토링
  cookie/public/assets/images/movie/pencil.svg
  cookie/src/components/movieDetailPage/CastSection.jsx
  cookie/src/components/movieDetailPage/DetailsSection.jsx
  cookie/src/components/movieDetailPage/ReviewSection.jsx
  cookie/src/components/movieDetailPage/VideoSection.jsx
  cookie/src/pages/MovieDetail.jsx
Labels: 🚀 Refactor

#223 Refactor: #221 리뷰 작성 페이지 UI 수정
  cookie/src/components/layout/Header.jsx
  cookie/src/components/searchpage/ReviewHeader.jsx
  cookie/src/pages/ReviewForm.jsx
Labels: 🚀 Refactor

#229 Refactor:#228 매치업 리팩토링
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/components/common/LoginModal.jsx
  cookie/src/components/layout/Footer.jsx
  cookie/src/components/main/MatchUpSection.jsx
  cookie/src/components/matchup/Modal.jsx
  cookie/src/components/matchup/Poster.jsx
  cookie/src/components/matchup/PosterList.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/stores/useUserStore.js
Labels: 🚀 Refactor

#237 Feat/#234 페이지 반응형
  cookie/src/components/movieDetailPage/GallerySection.jsx
  cookie/src/components/searchpage/SearchResults.jsx
  cookie/src/pages/MovieDetail.jsx
Labels: 🍿 Feat

#236 Fix: 수정할때 평점도 수정되게 + 로그인한 유저에 따라서 토글메뉴 visibility 처리
  cookie/src/components/searchpage/DeleteConfirmationModal.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/pages/ReviewDetail.jsx
Labels: 🚀 Refactor

#238 feat: 영화 상세페이지 스틸컷 적응형
  cookie/src/components/movieDetailPage/HeaderSection.jsx
Labels: 🍿 Feat

#239 feat: 검색 모바일 반응형 피드백 반영
  cookie/src/pages/search.jsx
Labels: 🍿 Feat

#240 Refactor/#235 my page liked
  cookie/public/assets/images/camera.svg
  cookie/src/components/matchup/PointSection.jsx
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/pages/DetailReview.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedReviews.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🚀 Refactor

#244 feat: 리뷰 피드 페이지 모바일 반응형
  cookie/src/pages/ReviewFeed.jsx
Labels: 🍿 Feat

#245 Refactor: back ground color
  cookie/public/assets/images/review/heart-review.svg
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/searchpage/ReviewContentSection.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/MyAllReviewList.jsx
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/styles/global.js
Labels: 🚀 Refactor

#247 Refactor/#243-전체적으로 리팩토링
  cookie/public/assets/gif/accessnotification.gif
  cookie/src/components/common/Popup.jsx
  cookie/src/components/matchup/ChartSection.jsx
  cookie/src/components/matchup/ChatContainer.jsx
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/components/signUp/Modal.jsx
  cookie/src/pages/PointHistoryPage.jsx
Labels: 🚀 Refactor

#248 Refactor/#232 main refactor
  cookie/src/assets/images/main/cookie_icon.svg
  cookie/src/assets/images/main/edit-pencil.svg
  cookie/src/assets/images/main/fight_icon.svg
  cookie/src/assets/images/main/like-heart.svg
  cookie/src/assets/images/main/like-heart2.svg
  cookie/src/assets/images/main/matchup_icon.svg
  cookie/src/assets/images/main/rank_1.svg
  cookie/src/assets/images/main/rank_10.svg
  cookie/src/assets/images/main/rank_2.svg
  cookie/src/assets/images/main/rank_3.svg
  cookie/src/assets/images/main/rank_4.svg
  cookie/src/assets/images/main/rank_5.svg
  cookie/src/assets/images/main/rank_6.svg
  cookie/src/assets/images/main/rank_7.svg
  cookie/src/assets/images/main/rank_8.svg
  cookie/src/assets/images/main/rank_9.svg
  cookie/src/assets/images/main/reviews.svg
  cookie/src/assets/images/main/special_icon.svg
  cookie/src/assets/images/main/video_icon.svg
  cookie/src/components/admin/BadgeList.jsx
  cookie/src/components/layout/Header.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/Footer.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUpSection.jsx
  cookie/src/components/main/Question.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/components/searchpage/TopButton.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/admin/AdminBadge.jsx
  cookie/src/pages/main.jsx
Labels: 🚀 Refactor

#251 refactor : #249 메인스크롤 및 아이콘 경로수정
  cookie/public/assets/images/main/like-heart2.svg
  cookie/public/assets/images/main/reviews.svg
  cookie/src/components/common/Popup.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
Labels: 🚀 Refactor

#252 feat: 특정영화리뷰피드 반응형 초안
  cookie/src/pages/MovieReviewFeed.jsx
Labels: 🍿 Feat

#253 Refactor: #249 메인 이미지 반응형 적용
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUpSection.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/components/searchpage/TopButton.jsx
  cookie/src/pages/main.jsx
Labels: 🚀 Refactor

#256 Feat/#234 페이지 반응형
  cookie/src/pages/MovieReviewFeed.jsx
Labels: 🍿 Feat

#257 hotfix: 반응형 CSS 수정
  cookie/src/pages/MovieReviewFeed.jsx
Labels: 🍿 Feat

#261 Refactor: 배우 및 감독 상세 페이지 UI 수정 및 반응형 적용
  cookie/public/assets/images/review/reviews-review.svg
  cookie/src/components/movieDetailPage/CastDetail.jsx
Labels: 🚀 Refactor

#263 특정 영화 리뷰 피드페이지 인기순 정렬 추가
  cookie/src/pages/MovieReviewFeed.jsx
Labels: 🍿 Feat

#264 Refactor #259 관리자페이지 리펙토링
  cookie/src/assets/images/admin/award.svg
  cookie/src/assets/images/admin/cookie.svg
  cookie/src/assets/images/admin/like.svg
  cookie/src/assets/images/admin/movie.svg
  cookie/src/assets/images/admin/setting.svg
  cookie/src/components/admin/AddBadge.jsx
  cookie/src/components/admin/BadgeList.jsx
  cookie/src/components/admin/CommentsModal.jsx
  cookie/src/components/admin/CookieMovieList.jsx
  cookie/src/components/admin/EditMatchUp.jsx
  cookie/src/components/admin/LikeList.jsx
  cookie/src/components/admin/Likes.jsx
  cookie/src/components/admin/LikesModal.jsx
  cookie/src/components/admin/MatchUpList.jsx
  cookie/src/components/admin/ReviewList.jsx
  cookie/src/components/admin/Reviews.jsx
  cookie/src/components/admin/SearchModal.jsx
  cookie/src/components/admin/SearchMovieDetail.jsx
  cookie/src/components/admin/SideBar.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUpSection.jsx
  cookie/src/components/main/Question.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/components/searchpage/TopButton.jsx
  cookie/src/pages/CategoryMovieFeed.jsx
  cookie/src/pages/main.jsx
Labels: 🚀 Refactor

#267 Refactor/#265 전체 적인 리펙토링
  cookie/src/assets/images/admin/award.svg
  cookie/src/assets/images/admin/badge3.svg
  cookie/src/assets/images/admin/cookie.svg
  cookie/src/assets/images/admin/cookieLogo.svg
  cookie/src/assets/images/admin/cookie_img.svg
  cookie/src/assets/images/admin/empty_cookie.svg
  cookie/src/assets/images/admin/empty_cookie2.svg
  cookie/src/assets/images/admin/movie.svg
  cookie/src/assets/images/admin/movies.svg
  cookie/src/assets/images/admin/setting.svg
  cookie/src/components/admin/AddBadge.jsx
  cookie/src/components/admin/AddMatchUp.jsx
  cookie/src/components/admin/Addmovie.jsx
  cookie/src/components/admin/AdminMovie.jsx
  cookie/src/components/admin/BadgeList.jsx
  cookie/src/components/admin/CommentsModal.jsx
  cookie/src/components/admin/CookieMovieList.jsx
  cookie/src/components/admin/EditBadgeModal.jsx
  cookie/src/components/admin/EditCategory.jsx
  cookie/src/components/admin/EditMatchUp.jsx
  cookie/src/components/admin/Likes.jsx
  cookie/src/components/admin/LikesModal.jsx
  cookie/src/components/admin/MatchUpDetailModal.jsx
  cookie/src/components/admin/MatchUpList.jsx
  cookie/src/components/admin/MovieInfoModal.jsx
  cookie/src/components/admin/Pagination.jsx
  cookie/src/components/admin/ReviewList.jsx
  cookie/src/components/admin/Reviews.jsx
  cookie/src/components/admin/SearchModal.jsx
  cookie/src/components/admin/SearchMovieDetail.jsx
  cookie/src/components/admin/SideBar.jsx
  cookie/src/components/main/AdminRecommend.jsx
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/Question.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/components/movieDetailPage/CastDetail.jsx
  cookie/src/pages/admin/AdminBadge.jsx
  cookie/src/pages/admin/AdminLogin.jsx
  cookie/src/pages/admin/AdminMatchUp.jsx
  cookie/src/pages/admin/AdminMovie.jsx
  cookie/src/pages/admin/AdminReviewLike.jsx
  cookie/src/pages/admin/BadgeList.jsx
  cookie/src/pages/main.jsx
  cookie/src/stores/useAdminMovieStore.js
  cookie/src/stores/useAuthStore.js
  cookie/src/stores/useMovieGategoryStore.js
  cookie/src/stores/useUserStore.js
Labels: 🚀 Refactor

#269 Update: #265 포스터 업로드 오류 수정
  cookie/src/assets/images/admin/Edit_white.svg
  cookie/src/components/admin/AddLinkStillCut.jsx
  cookie/src/components/admin/EditCategory.jsx
  cookie/src/components/admin/EditMatchUp.jsx
  cookie/src/components/admin/MatchUpList.jsx
  cookie/src/components/admin/SearchModal.jsx
Labels: 🚀 Refactor
