Repository URECA-Cookie/Cookie-FE, pull requests merged in 2024-11, with the labels that each got.

#5 Feat : 헤더 생성
  cookie/.gitignore
  cookie/package-lock.json
  cookie/package.json
  cookie/src/App.css
  cookie/src/App.jsx
  cookie/src/assets/images/Cookie.svg
  cookie/src/assets/images/Notification.svg
  cookie/src/components/mypage/Header.jsx
  cookie/src/components/mypage/Navvar.jsx
  cookie/src/index.css
  cookie/src/pages/main.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/AppPages.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/PrivateRoute.jsx
  cookie/src/routes/RouteDef.jsx
Labels: Feat

#7 Feat :하단네비바 완성 및 헤더,라우터 수정
  cookie/package-lock.json
  cookie/package.json
  cookie/src/assets/images/navbar_home.svg
  cookie/src/assets/images/navbar_matchup.svg
  cookie/src/assets/images/navbar_profile.svg
  cookie/src/assets/images/navbar_review.svg
  cookie/src/assets/images/navbar_search.svg
  cookie/src/components/Header.jsx
  cookie/src/components/Navvar.jsx
  cookie/src/components/mypage/Navvar.jsx
  cookie/src/pages/main.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#17 Feature/#7 my page
  cookie/package-lock.json
  cookie/package.json
  cookie/src/App.css
  cookie/src/assets/images/mypage/actionbadge.svg
  cookie/src/assets/images/mypage/cookiescore.svg
  cookie/src/assets/images/mypage/hearticon.svg
  cookie/src/assets/images/mypage/manageprofile.svg
  cookie/src/assets/images/mypage/reviewticket.svg
  cookie/src/assets/images/mypage/romancebadge.svg
  cookie/src/assets/images/mypage/sfbadge.svg
  cookie/src/assets/images/mypage/shareicon.svg
  cookie/src/components/Header.jsx
  cookie/src/components/Navvar.jsx
  cookie/src/components/mypage/BadgeList.jsx
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/GenreChart.jsx
  cookie/src/components/mypage/LogoutAndWithdraw.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/index.css
  cookie/src/main.jsx
  cookie/src/pages/main.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#20 Refactor: 영화 검색 페이지 컴포넌트화
  cookie/package-lock.json
  cookie/src/components/searchpage/MovieListSection.jsx
  cookie/src/components/searchpage/SearchBar.jsx
  cookie/src/components/searchpage/SearchResults.jsx
  cookie/src/components/searchpage/TopButton.jsx
  cookie/src/pages/search.jsx
  cookie/yarn.lock
Labels: 🚀 Refactor

#21 [Feat] 회원가입 페이지 UI구현
  cookie/src/assets/images/signUp/close_icon.svg
  cookie/src/assets/images/signUp/user_img.svg
  cookie/src/pages/Login.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/SignUpTheme.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/stores/useUserStore.js
  cookie/src/styles/login/login.js
Labels: 🍿 Feat

#23 Feature/#15 manage profile
  cookie/src/assets/images/mypage/defaultbadge.svg
  cookie/src/assets/images/mypage/defaultimage.svg
  cookie/src/assets/images/mypage/ic_back.svg
  cookie/src/assets/images/mypage/ic_camera.svg
  cookie/src/assets/images/mypage/setimage.svg
  cookie/src/components/Header.jsx
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#25 Feat/#24 liked movies page
  cookie/src/assets/images/mypage/red-heart.svg
  cookie/src/components/Header.jsx
  cookie/src/components/Navvar.jsx
  cookie/src/components/ScrollToTop.jsx
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/components/searchpage/SearchBar.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/main.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/pages/search.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#27 Fix: import 오류 해결
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/MovieDetail.jsx
  cookie/src/pages/main.jsx
  cookie/src/pages/mypage.jsx
Labels: 👿Bug

#29 Design: 카드형태 무너진것 수정
  cookie/src/pages/LikedMovies.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🚀 Refactor

#31 Design: 리뷰티켓 반응형 완료
  cookie/src/components/mypage/ReviewList.jsx
Labels: 🚀 Refactor

#34 Feature/#32 detailreview
  cookie/src/assets/images/mypage/More.svg
  cookie/src/components/mypage/DetailHeader.jsx
  cookie/src/components/mypage/FavoriteList.jsx
  cookie/src/components/mypage/FooterSection.jsx
  cookie/src/components/mypage/GenreChart.jsx
  cookie/src/components/mypage/ReviewContentSection.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/components/mypage/ReviewTextSection.jsx
  cookie/src/pages/DetailReview.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedRevies.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#38 Feat: MYPAGE API MAPPING
  cookie/src/components/mypage/BadgeList.jsx
  cookie/src/components/mypage/GenreChart.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#39 Feature/#37 apimypage
  cookie/src/components/mypage/BadgeList.jsx
  cookie/src/components/mypage/ReviewList.jsx
  cookie/src/pages/DetailReview.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/LikedRevies.jsx
  cookie/src/pages/mypage.jsx
Labels: 🍿 Feat

#41 Feature/#12 movie detail page
  cookie/package-lock.json
  cookie/package.json
  cookie/src/components/movieDetailPage/ArrowButton.jsx
  cookie/src/components/movieDetailPage/CastSection.jsx
  cookie/src/components/movieDetailPage/DetailsSection.jsx
  cookie/src/components/movieDetailPage/GallerySection.jsx
  cookie/src/components/movieDetailPage/HeaderSection.jsx
  cookie/src/components/movieDetailPage/ReviewSection.jsx
  cookie/src/components/movieDetailPage/VideoSection.jsx
  cookie/src/components/searchpage/MovieListSection.jsx
  cookie/src/components/searchpage/SearchBar.jsx
  cookie/src/pages/MovieDetail.jsx
  cookie/src/pages/search.jsx
  cookie/yarn.lock
  package-lock.json
Labels: 🍿 Feat

#40 Feat: 프로필 관리 매핑
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/pages/ManageProfile.jsx
Labels: 🍿 Feat

#35 [feat] 메인페이지 퍼블리싱
  cookie/src/App.jsx
  cookie/src/assets/images/main/cookie_icon.svg
  cookie/src/assets/images/main/fight_icon.svg
  cookie/src/assets/images/main/matchup_icon.svg
  cookie/src/assets/images/main/rank_1.svg
  cookie/src/assets/images/main/rank_10.svg
  cookie/src/assets/images/main/rank_2.svg
  cookie/src/assets/images/main/rank_3.svg
  cookie/src/assets/images/main/rank_4.svg
  cookie/src/assets/images/main/rank_5.svg
  cookie/src/assets/images/main/rank_6.svg
  cookie/src/assets/images/main/rank_7.svg
  cookie/src/assets/images/main/rank_8.svg
  cookie/src/assets/images/main/rank_9.svg
  cookie/src/assets/images/main/special_icon.svg
  cookie/src/assets/images/main/video_icon.svg
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUpContainer.jsx
  cookie/src/components/main/RankMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/SignUpTheme.jsx
  cookie/src/pages/main.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat

#43 Feature/#42 check nick name
  cookie/package-lock.json
  cookie/package.json
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/pages/LikedMovies.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/yarn.lock
Labels: 🍿 Feat

#45 Feature/#44 push notification
  cookie/src/components/Notification.jsx
  cookie/src/components/mypage/BadgeList.jsx
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/pages/ManageProfile.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/mypage.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat

#47 Feature/#36 matchup
  cookie/package-lock.json
  cookie/package.json
  cookie/src/assets/images/matchup/ic_bigfight.svg
  cookie/src/assets/images/matchup/ic_fight.svg
  cookie/src/assets/images/matchup/sampleimage1.svg
  cookie/src/assets/images/matchup/sampleimage2.svg
  cookie/src/assets/images/matchup/topic_image.svg
  cookie/src/components/Notification.jsx
  cookie/src/components/matchup/ChartSection.jsx
  cookie/src/components/matchup/Modal.jsx
  cookie/src/components/matchup/Poster.jsx
  cookie/src/components/matchup/PosterList.jsx
  cookie/src/components/matchup/ProgressBar.jsx
  cookie/src/components/matchup/RadarChart.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/yarn.lock
Labels: 🍿 Feat

#48 Feature/#36 matchup
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#52 Feat/#46 Oauth login
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/api/auth/axiosInstance.js
  cookie/src/components/main/CookieMovies.jsx
  cookie/src/components/main/GenreMovie.jsx
  cookie/src/components/main/MatchUp.jsx
  cookie/src/components/main/RankMovie.jsx
  cookie/src/components/main/SpecialMovie.jsx
  cookie/src/config/OAuthConfig.js
  cookie/src/config/apiConfig.js
  cookie/src/pages/Login.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/pages/SignUpTheme.jsx
  cookie/src/pages/main.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/styles/global.js
Labels: 🍿 Feat

#53 feat: 회원가입페이지 닉네임 중복확인 api연동 완료
  cookie/src/api/auth/ReTokenPage.jsx
  cookie/src/api/auth/axiosInstance.js
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#55 Feature/#49 refactor match up
  cookie/package-lock.json
  cookie/package.json
  cookie/src/components/matchup/ChartSection.jsx
  cookie/src/components/matchup/Modal.jsx
  cookie/src/components/matchup/Poster.jsx
  cookie/src/components/matchup/PosterList.jsx
  cookie/src/components/matchup/ProgressBar.jsx
  cookie/src/components/matchup/RadarChart.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/components/matchup/TitleSection.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/yarn.lock
Labels: 🚀 Refactor

#56 feat: 회원가입완료시 토큰 발급 api 추가
  cookie/src/App.jsx
  cookie/src/api/auth/axiosInstance.js
  cookie/src/assets/images/admin/award.svg
  cookie/src/assets/images/admin/cookie.svg
  cookie/src/assets/images/admin/cookieLogo.svg
  cookie/src/assets/images/admin/cookie_sm.svg
  cookie/src/assets/images/admin/logout.svg
  cookie/src/assets/images/admin/movie.svg
  cookie/src/assets/images/admin/setting.svg
  cookie/src/components/admin/SideBar.jsx
  cookie/src/pages/AdminLogin.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#58 Feat: 로고 클릭시 home으로 설정
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat

#61 Feat/#54 admin login
  cookie/src/api/auth/axiosInstance.js
  cookie/src/assets/images/admin/CookieAdmin.svg
  cookie/src/assets/images/admin/cookie_img.svg
  cookie/src/pages/AdminLogin.jsx
Labels: 🍿 Feat

#64 Feature/#62 push notification
  cookie/package-lock.json
  cookie/package.json
  cookie/src/components/Notification.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/stores/notificationStore.js
  cookie/yarn.lock
Labels: 🍿 Feat

#65 Feat: 회원가입 페이지 모달구현
  cookie/.gitignore
  cookie/src/api/auth/axiosInstance.js
  cookie/src/assets/images/admin/award.svg
  cookie/src/assets/images/admin/cookie.svg
  cookie/src/assets/images/admin/cookie_sm.svg
  cookie/src/assets/images/admin/logout.svg
  cookie/src/assets/images/admin/movie.svg
  cookie/src/assets/images/admin/setting.svg
  cookie/src/components/admin/SideBar.jsx
  cookie/src/components/main/RankMovie.jsx
  cookie/src/components/signUp/Modal.jsx
  cookie/src/config/apiConfig.js
  cookie/src/pages/AdminLogin.jsx
  cookie/src/pages/SignUpGenre.jsx
  cookie/src/pages/SignUpProfile.jsx
Labels: 🍿 Feat

#68 Feature/#66 design chatting
  cookie/src/assets/images/matchup/chatsendbutton.svg
  cookie/src/components/matchup/ChatContainer.jsx
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat

#72 Feat/#72 chatting
  cookie/package-lock.json
  cookie/package.json
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/pages/MatchupPage.jsx
  cookie/vite.config.js
  cookie/yarn.lock
Labels: 🍿 Feat

#76 Feat/#75 review detail
  cookie/src/pages/ReviewDetail.jsx
  cookie/src/pages/ReviewFeed.jsx
  cookie/src/routes/RouteDef.jsx
Labels: 🍿 Feat

#79 Fix/#78 fix mobile screen
  cookie/index.html
  cookie/src/App.jsx
  cookie/src/routes/AppScreen.jsx
  cookie/src/styles/global.js
Labels: 🍿 Feat

#82 Feature/#82 responsive match up
  cookie/src/components/matchup/ChartSection.jsx
  cookie/src/components/matchup/ChatInput.jsx
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/PosterList.jsx
  cookie/src/components/matchup/Timer.jsx
  cookie/src/pages/MatchupPage.jsx
Labels: 🍿 Feat

#81 feat 관리자페이지 영화 등록화면 구현
  cookie/src/App.jsx
  cookie/src/assets/images/admin/cookieMovie.svg
  cookie/src/assets/images/admin/cookie_sm.svg
  cookie/src/assets/images/admin/frame.svg
  cookie/src/assets/images/admin/goBack.svg
  cookie/src/components/admin/AddLinkStillCut.jsx
  cookie/src/components/admin/Addmovie.jsx
  cookie/src/components/admin/MovieList.jsx
  cookie/src/components/admin/SearchMovieDetail.jsx
  cookie/src/components/admin/SearchMovieList.jsx
  cookie/src/components/admin/SideBar.jsx
  cookie/src/pages/admin/AdminLogin.jsx
  cookie/src/pages/admin/AdminMovie.jsx
  cookie/src/routes/RouteDef.jsx
  cookie/src/stores/useAdminMovieStore.js
Labels: 🍿 Feat

#87 Refactor: 채팅 UI 반응형 적용:
  cookie/src/components/matchup/ChatMessages.jsx
  cookie/src/components/matchup/ChatUI.jsx
  cookie/src/pages/MatchupPage.jsx
Labels: 🚀 Refactor

#85 Feature/#85 toggle switch
  cookie/src/components/ToggleSwitch.jsx
  cookie/src/routes/AppScreen.jsx
Labels: 🍿 Feat

#89 Feature/#88 responsive mypage
  cookie/src/assets/images/mypage/setdefaultImage.svg
  cookie/src/components/mypage/BadgeSelector.jsx
  cookie/src/components/mypage/NicknameInput.jsx
  cookie/src/components/mypage/ProfileImage.jsx
  cookie/src/components/mypage/SaveProfileButton.jsx
  cookie/src/components/mypage/SetGenre.jsx
  cookie/src/components/mypage/SetProfileImage.jsx
  cookie/src/pages/ManageProfile.jsx
Labels: 🍿 Feat
